### ISSUE TITLE
Prepoznavanje profesije i pola osobe

### ISSUE THREAD

**Issue by aleksandarb99** [ftn-ai-lab/sc-2021-siit#1]
Tim
Jovan Simic SW26-2018,
Jelena Stojanovic SW79-2018,
Aleksandar Buljevic SW25-2018

Asistent
Milica Škipina

Definicija problema
Prepoznavanje profesije i pola osobe sa slike upotrebom CNN-a

Metodologija
- Detekcija osobe/osoba s slike pomocu HOG-a
- Detekcija lica osobe
- Klasifikacija profesije upotrebom treniranog CNN-a
- Klasifikacija pola upotrebom treniranog CNN-a

Skup podataka
Koriscenje trening skupa za treniranje mreze za prepoznavanje profesije sa linka, slike samo sa pojedinacnim osobama: 
https://github.com/ninja3697/Profession-Detection-System/tree/master/idenprof/train

Koriscenje trening skupa za treniranje mreze za prepoznavanje pola:
https://www.kaggle.com/cashutosh/gender-classification-dataset

Test skup: 
https://github.com/ninja3697/Profession-Detection-System/tree/master/idenprof/test
Koriscenjem HOG-a i sliding window-a sa testnih slika prepoznaju se osobe i
salju se pojedinacne izdvojene slike tih osoba dalje na prepoznavanje profesije.
Nakon toga se sa pojedinacnih slika izdvaja lice osobe i salje na prepoznavanje pola.

Evaluacija
Kada istreniramo model, proci cemo kroz rezultate i videti sta je model uokvirio, da li je uopste uokvirio osobu i da li je prepoznato odgovarajuce zanimanje. Na osnovu dobrih ili losih rezultata izracunacemo tacnost modela za detekciju osoba. Metrika koju cemo koristiti je preciznost. 
Sto se tice CNN-ova, tacnost ce se racunati upoređivanjem prediktovane i stvarne profesije, kao i upoređivanjem prediktovanog i stvarnog pola na testnom skupu slika.

Link ka repozitorijumu
https://github.com/aleksandarb99/profession-and-gender-recognition/tree/develop

**Comment by milica-skipina** [comment]
Pošto rješavanje problema zahtjeva upotrebu skupa podataka, potrebno je opisati koji skup/skupove planirate da koristite.

**Comment by aleksandarb99** [comment]
Dodali smo link ka podacima.

**Comment by milica-skipina** [comment]
Na koji način će biti labelirani podaci za problem prepoznavanja pola osobe? 

Projekat nema dovoljnu složenost za najveću ocjenu za tim od tri člana.
Da li ćete:
        1. Ipak raditi ovaj projekat?
        2. Korigovati prijavu tako da se projekat proširi da radi detekciju na videu?
        3. Redukovati tim na dva člana?
        4. Prijaviti drugu temu?

**Comment by aleksandarb99** [comment]
Zdravo Milice,

Sto se tice laberiranja podataka, rucno cemo popuniti labele.
Ukoliko bi ipak radili ovaj projekat, a vi ste rekli da on nije za najvecu
ocenu, da li to znaci da s njim mozemo dobiti 9?

Srdacan pozdrav!

пон, 13. дец 2021. у 19:29 Milica Škipina ***@***.***> је
написао/ла:

**Comment by aleksandarb99** [comment]
Zdravo Milice,

Prepravili smo nedostatke na koje ste nam ukazali.

Srdacan pozdrav!

**Comment by milica-skipina** [comment]
Korigujte evaluaciju tako što ćete dodati i metriku za detekciju osoba.

**Comment by aleksandarb99** [comment]
Zdravo Milice,

Izmenili smo evaluaciju.

Srdacan pozdrav!

**Comment by aleksandarb99** [comment]
Zdravo Milice,

Izmenili smo evaluaciju.

Srdacan pozdrav i srecni praznici :D!

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
