### ISSUE TITLE
Detekcija, lokalizacija i klasifikacija civilnih i vojnih vozila

### ISSUE THREAD

**Issue by dusanbrkic** [ftn-ai-lab/sc-2021-siit#10]
## Tim:
- Brkić Dušan - SW-42/2018
- Živanac Filip- SW-66/2018
## Asistent:
- Vidaković Dragan
## Definicija problema:
Detekcija, lokalizacija i klasifikacija civilnih i vojnih vozila ("military truck", "military tank", "military aircraft", "military helicopter", "civilian car", "civilian aircraft") na slikama.
## Skup podataka:
Koristicemo labelirane slike razlicitih dimenzija sa [linka](https://data.mendeley.com/datasets/njdjkbxdpn/1).
## Metodologija:
Koristicemo neki algoritam iz YOLO porodice algoritama i to gotov model. Najverovatnije YOLOv5.
Repozitorijum: [soft-p](https://github.com/dusanbrkic/soft-p)
## Evaluacija:
- Detekcija i klasifikacija: Precision, Recall, F-Score.
- Lokalizacija: mAP (mean Average Precision).

**Comment by vdragan1993** [comment]
Zamolio bih vas da preciznije opišete skup podataka. 

Koje tačno algoritme iz YOLO porodice planirate da koristite? 
Da li će modeli biti ručno implementirani, ili će se koristiti gotovi?

**Comment by dusanbrkic** [comment]
Najverovatnije ce biti YOLOv5 i koristicemo gotov model.

Sto se tice skupa podataka, sta je jos potrebno opisati?
Na linku se nalaze nekih 6,7k slika na kojima su pomenute klase, na nekima i vise klasa, za koje postoje za svaku sliku naziv klase prikazanog objekta i koordinate bounding boxa u kom se objekat nalazi.

**Comment by vdragan1993** [comment]
Potrebno je opisati ili ukloniti deo `ukoliko se predomislimo`.

**Comment by dusanbrkic** [comment]
Izgleda onda da nema predomisljavanja :(

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
