### ISSUE TITLE
Detekcija karata i određivanje najboljeg poteza u igri tablić

### ISSUE THREAD

**Issue by nikolinat** [ftn-ai-lab/sc-2021-siit#11]
### **Tim:**

-  Dragana Filipović, SW-47-2018
-  Nikolina Tošić, SW-36-2018

### **Asistent:**

- Dragan Vidaković

### **Definicija problema:**
Na osnovu karata koje se nalaze na talonu, kao i karata koje igrač ima u rukama vrši se njihova detekcija i predviđa se najbolji potez koji igrač može da odigra.

### **Skup podataka:**
Skup podataka ćemo same kreirati, uz korišćenje augmentacije podataka.

### **Metodologija:**
Koristiće se YOLOv3 algoritam (gotov model) za prepoznavanje karata sa slika. Sumiraće se vrednost svake karte, kao i broj karata koje igrač može da pokupi sa talona i analizom toga izračunaće se najbolji potez. Posebnim kartama će biti dodeljena veća vrednost.

### **Evaluacija:**
Za klasifikaciju, kao i evaluaciju detekcije karata koristiće se accuracy.

**Comment by vdragan1993** [comment]
Proširite evaluaciju tako da uključuje evaluaciju detekcije karata ili evaluaciju kvaliteta predlaganja poteza.

**Comment by nikolinat** [comment]
Pozdrav,
Evaluacija je ispravljena.

**Comment by vdragan1993** [comment]
Koja metrika će se koristiti prilikom računanja tačnosti detekcije?

**Comment by nikolinat** [comment]
Koristićemo IoU metriku.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by nikolinat** [comment]
Link ka repozitorijumu: [https://github.com/nikolinat/soft-computing](url)
