### ISSUE TITLE
Detekcija i klasifikacija Pokemona

### ISSUE THREAD

**Issue by RajnovicTeodora** [ftn-ai-lab/sc-2021-siit#13]
**Tim:**
Teodora Rajnović - SW-67/2018

**Asistent:**
Vidaković Dragan

**Definicija problema:**
Detekcija i klasifikacija Pokemona na slici. Algoritam treba da prepozna Pokemona sa slike i da odredi kojoj od 10 klasa pripada.

**Skup podataka:**
Kao skup podataka koristiće se slike prikupljene sa više različitih izvora sa interneta.

**Metodologija:**
Za detekciju ću koristiti HOG, a za klasifikaciju CNN.

**Evaluacija:**
Skup podataka će biti podeljen na trening, test i validacioni skup. Kao metrika evaluacije će se koristiti accuracy (tačnost). Za evaluaciju koraka detekcije će se koristiti IoU metrika.

**Repozitorijum:**
https://github.com/RajnovicTeodora/pokemon-detection-and-classification

**Comment by vdragan1993** [comment]
Proširite evaluaciju tako da uključuje i evaluaciju koraka detekcije.

**Comment by RajnovicTeodora** [comment]
Pozdrav, proširila sam evaluaciju.

**Comment by vdragan1993** [comment]
IoT kao metrika (koliko ja znam) ne postoji. Da li ste mislili `IoU`?

**Comment by RajnovicTeodora** [comment]
Da, mislim na IoU metriku za poređenje bounding box-ova. Ispravila sam grešku.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
