### ISSUE TITLE
Detekcija i klasifikacija da li osobe na slici nose maske

### ISSUE THREAD

**Issue by HajdukDusan** [ftn-ai-lab/sc-2021-siit#16]
### Tim:

- Hajduk Dušan (sw40-2018)

### Asistent:
Dragan Vidaković

### Definicija problema:
Detekcija, i klasifikacija da li osobe na slici nose maske.

### Skup podataka:
Skup podataka biće preuzet sa [kaggle.com](https://www.kaggle.com/andrewmvd/face-mask-detection)
On sadrži slike ljudi koji nose i ne nose maske, sve slike su labelirane i sadrže bounding box-ove.

### Metodologija:

Multiklasna klasifikacija, gde delimo da li osoba nosi masku ili ne.
Klasifikacija će biti uradjena uz pomoć SVM-a.
Podelićemo problem na dva binarna klasifikatora.
Završnu predikciju određujemo preko nivoa sigurnosti klasifikatora tj daljine od margine.
Detekcija svakog lica (sa ili bez maske) na slici biće odrađena uz pomoć Sliding Window tehnike.

### Evaluacija:
Accuracy, Confusion Matrix, IoU 

### Repozitorijum
https://github.com/HajdukDusan/MaskDetector

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
