### ISSUE TITLE
Probrojavanje objekata na pokretnoj traci

### ISSUE THREAD

**Issue by DusanAnticc** [ftn-ai-lab/sc-2021-siit#17]
### Tim:  
- Loreana Oluić SW-60/2018
- Nemanja Milutinović SW-64/2018
- Dušan Antić SW-81/2019

### Asistent:
- Vidaković Dragan

### Definicija problema:
Detekcija, prebrojavanje i klasifikacija artikala na pokretnoj traci kase u marketu ("Banana","Apple","Sandwich","Carrot","Bottle")  na slici i videu.

### Skup podataka:
Koristimo YOLO modele koji su prethodno istrenirani na COCO skupu podataka.
Testiraćemo nad skupom podataka koji smo sami prikupili i anotirali, a modeli ce biti testirani na slikama i videima

### Metodologija:
Detekcija, prebrojavanje i klasifikacija artikala će se vršiti pomoću YOLO modela 
YOLOv3
YOLOV3-tiny
YOLOv4
YOLOv4-tiny

### Evaluacija:
- Procenat uspešnosti detekcije određenog artikla 
- Procenat uspešnosti klasifikacije svih artikala.

Koristićemo precision za detekciju i MAE za prebrojavanje

### Github
https://github.com/DusanAnticc/YOLO_object_detection

**Comment by vdragan1993** [comment]
Koja metrika će se koristiti prilikom određivanja uspešnosti detekcije?

Proširite evaluaciju tako što ćete uvesti metriku za evaluaciju procesa prebrojavanja.

**Comment by DusanAnticc** [comment]
Dodali smo metrike

**Comment by vdragan1993** [comment]
Koja metrika će se koristiti prilikom određivanja uspešnosti detekcije?

**Comment by DusanAnticc** [comment]
Average Precision

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
