### ISSUE TITLE
Šah upravljan govorom (srpski)

### ISSUE THREAD

**Issue by Lule99** [ftn-ai-lab/sc-2021-siit#18]
## Tim:

- Njegoš Blagojević SW-18/2018
- Đorđe Njegić SW-12/2018
- Luka Kureljušić SW-23/2018

## Asistenti:

- Dragan Vidaković 
- Milica Škipina

## Definicija problema:

Ideja je implementacija igre šah koja će se kontrolisati govorom, odnosno gde će se govor koristiti za selekciju polja i pomeranje figura. Takođe, predviđeno je da se omogući više različitih težina igre.

## Skup podataka:

1. Kako je igra zamišljena za srpsko govorno područije, sami ćemo prikupljati i snimati trening podatke i osloniti se na augmentaciju (ubrzavanje/usporenje zvuka, dodavanje whitenoisa u pozadini, glasno/tiho i slično).
2. Za potrebe obuke jednog od algoritama (MCTS sa neuronskom mrežom za evaluaciju table), koristićemo dataset na [linku](https://database.lichess.org/).

## Metodologija:
1. Klasifikacija zvuka osloniće se na upotrebu konvolutivne neuronske mreže (naša arhitektura) koju ćemo obučiti na prethodno prikupljenom datasetu, a kojoj ćemo prosleđivati melspectrogram-e audio fajlova. CNN će najverovatnije imati 16 klasa (1-8 i a-h).
2. Za implementaciju bota koristićemo dva algoritma. Prvi minimax, sa alpha-beta pruningom. Drugi algoritam koristio bi MonteCarlo Tree Search, koji bi za evaluaciju koristio neuronsku mrežu, obučenu na prethodno pomenutom datasetu.

## Evaluacija

Klasifikacija zvuka: Dataset će biti podeljen na trening (75%), validacioni(15%) i test (10%) skup. Te će se uspeh klasifikacije definisati u odnosu na test skup.

Efikasnost botova ćе se proveriti simulacijom igre sa nekim od online botova, na odgovarajućim težinama.

## Repozitorijum

https://github.com/Lule99/VoiceControlledChess

**Comment by milica-skipina** [comment]
Koja metrika će se koristiti prilikom određivanja uspješnosti klasifikacije zvuka?

**Comment by Lule99** [comment]
Za metriku će biti koriščen procenat uspešno klasifikovanih komandi na test skupu (accuracy).

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
