### ISSUE TITLE
Upravljanje muzičkom platformom Spotify pomoću pokreta ruke

### ISSUE THREAD

**Issue by jojev** [ftn-ai-lab/sc-2021-siit#19]
### Tim:
Vojnović Andrija - SW-7-2018
Jevtić Jovana - SW-20-2018

### Asistent:
Vidaković Dragan

### Definicija problema:
Detekcija ruke korisnika na videu i klasifikacija pokreta na osnovu kog se izvršavaju određene akcije na muzičkoj platformi Spotify. Akcije koje će bit podržane su:

- smanjivanje zvuka
- pojačavanje zvuka
- pauziranje pesme
- prebacivanje na sledeću pesmu
- prebacivanje na prethodnu pesmu

### Skup podataka:
Skup podataka koji će se koristiti za treniranje pronašli smo na sledećem [linku.]( https://www.kaggle.com/lakshmig/gesture-recognition-tv-volume-etc/notebook). Skup sadrži videe sa pet različitih akcija. Svaki video se sastoji od 30 frejmova. Testiranje ćemo izvršiti pomoću ručno snimljenih podataka i snimaka sa veb kamere u realnom vremenu.

### Metodologija:
Za klasifikaciju ćemo koristiti ručno pravljenu konvolucionu mrežu.

### Evaluacija:
Skup podataka će biti podeljen na trening skup(85%) i validacioni skup(15%).
Za evaluaciju će se koristiti accuracy.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by jojev** [comment]
Link ka Github repozitorijumu projekta: https://github.com/vAndrija/soft.
