### ISSUE TITLE
Detekcija, lokalizacija i klasifikacija učesnika u saobraćaju

### ISSUE THREAD

**Issue by ivanmrsulja** [ftn-ai-lab/sc-2021-siit#2]
## Tim:
 - Popović Miloš - SW-24/2018
 - Karanfilović Dimitrije - SW-39/2018
 - Mršulja Ivan - SW-65/2018

## Asistent:
- Vidaković Dragan

## Definicija problema:
Detekcija, lokalizacija i klasifikacija učesnika u saobraćaju ("car", "bus", "truck", "person") na videu, upotrebom različitih algoritama iz YOLO porodice.

## Skup podataka:
S ozbirom na to da se koriste algoritmi iz YOLO porodice i da koristimo transfer learning pristup trening podaci nisu potrebni (svi modeli su prethodno istrenirani na COCO skupu podataka). Testiranje će se izvršiti nad skupom podataka na [linku](https://public.roboflow.com/object-detection/self-driving-car/3/download/coco) kombinovano sa ručno anotiranim skupom podataka sa videa koje smo prikupili sa interneta. Ručno prikupljeni videi će se takođe koristiti za pravljenje demo-a.

## Metodologija:
Detekcija, klasifikacija i evaluacija će biti izvršene korišćenjem algoritama iz YOLO porodice i to:
- YOLOv3 (ručno implementiran) - ovo je ubačeno za potrebe učenja i uvida kako funkcioniše sam algoritam
- YOLOv3 (gotov model)
- YOLOv3-tiny (gotov model)
- YOLOv4-tiny (gotov model)

Težine za sve modele kao i konfiguracije gotovih modela će biti preuzete sa njihovih zvaničnih sajtova.

## Evaluacija:
Kao mera performanse za detekciju i klasifikaciju koristiće se preciznost, tačnost, odziv i F mera.
Kao mera performanse za lokalizaciju koristiće se mAP (mean average precision).
Kao mera performanse za rad u realnim uslovima koristiće se odnos prosečnog FPS-a (koliko frejmova po sekundi model može da obradi), mAP-a i F mere.

Performanse gore pomenutih modela biće evaluirane i međusobno poređene kako bi se odredio najbolji za primenu u ovom domenu.

**Comment by vdragan1993** [comment]
Zamolio bih da preciznije definišete nad kojim podacima će se vršiti testiranje.

Kako planirate da iskoristite prosečan FPS za meru performansi za rad u realnim uslovima?

**Comment by ivanmrsulja** [comment]
Pozdrav, ispravili smo issue u skladu sa sugestijama.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by ivanmrsulja** [comment]
Github repozitorijum: https://github.com/ivanmrsulja/traffic-participants-detection
