### ISSUE TITLE
Igranje Counter Strike pomoću pokreta očiju i ruke

### ISSUE THREAD

**Issue by lukaserbedzija** [ftn-ai-lab/sc-2021-siit#21]
## Članovi tima:

[Miloš Panić (sw19-2018)](https://github.com/panicmilos)
[Luka Šerbedžija (sw32-2018)](https://github.com/lukaserbedzija)

## Asistent:
[Milica Škipina](https://github.com/milica-skipina)

## Definicija problema:
Igranje Counter Strike u realnom vremenu kroz dve vrste pokreta: 

- Pokret rukom pomoću kojeg se zadaje komanda poput pucanja, promene oružja, punjenje municije i kupovina oružja (9 različitih pokreta)
- Pozicioniranje nišana pomoću pokreta očiju

## Skup podataka:
Skup podataka za pokrete ruke će biti ručno napravljen. Slike će biti pravljene iz više različitih uglova i različitog osvetljenja. Kako bi skup podataka bio što različitiji, sve slike će biti dodatno obrađene.

## Metodologija:
Ulaz u sistem predstavlja jedan frejm web kamere. Obrada frejma se odvija kroz dve nezavisne aktivnost koje se paralelno odvijaju: 

- Korišćenje [GazeTracking](https://github.com/antoinelame/GazeTracking) za detekciju pokreta očiju i na osnovu rezultata zadavanje komande za pozicioniranje nišana
- Izdvajanje šake od pozadine i klasifikacija položaja šake na komandu u igri, korišćenjem gotove CNN

## Evaluacija:
Skup podatak će biti podeljen na trening, validacioni i testni skup u odnosu 75:15:10. Kao glavna metrika za merenje performansi će se koristiti _accuracy_, odnosno procenat uspešnosti klasifikovanih položaja šake. Kao sporedna metrika će se koristiti _user experience_ i  meriće se empirijski.

## Repozitorijum:
https://github.com/lukaserbedzija/cnts

**Comment by milica-skipina** [comment]
Šta planirate da koristite za detekciju pokreta očiju?

**Comment by lukaserbedzija** [comment]
Dodat je link do rešenja za detekciju pokreta očiju.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
