### ISSUE TITLE
Detekcija i rešavanje Free Cell igre pasijansa

### ISSUE THREAD

**Issue by isidorasavic** [ftn-ai-lab/sc-2021-siit#22]
### Tim:
Isidora Savić sw-72-2018

### Asistent:
Dragan Vidaković

### Definicija problema:
Na osnovu ulazne slike analiziraće se raspored karata, njihova boja i broj. Zatim će se odrediti da li je pasijans moguće otvoriti, tj uspešno završiti ili ne.

### Skup podataka:
Za skup podataka će se korititi slike, početnih i srednjih stanja igre, koje ću sama sakupiti iz različitih pasijans igara.

### Metodologija:
  1. Pretvaranje slike u binarnu korišćenjem tresholda.
  2. Izdvajanje karata na tabli, kao i dodatnih 8 polja, i prepoznavanje brojeva i klasterovanje znakova karata, koristeci konvolucionu neuronsku mrežu.
  3. Rešavanje igre
  4. Prikaz koraka za rešavanje ukoliko je pasijans moguće otvoriti.

### Evaluacija:
  - Za evaluaciju detektovanja table koristiće se procenat tačno prepoznatih brojeva i znakova karata, kao i praznih polja (Free Cell) i polja temelja.
  - Za evaluaciju uspešnosti resavanja igre koristiće se procenat karata koji je složen na temelju, broj praznih polja (od moguća 4), kao i broj koraka potrebnih za rešavanje igre.

### Github repozitorijum:
https://github.com/isidorasavic/FreeCellSolver.git

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
