### ISSUE TITLE
Autonomna vožnja pomoću distribuiranog algoritma učenja uslovljavanjem

### ISSUE THREAD

**Issue by bjelicaluka** [ftn-ai-lab/sc-2021-siit#23]
### Članovi tima:
[Luka Bjelica (SW-21-2018)](https://github.com/bjelicaluka)

### Asistent:
[Milica Škipina](https://github.com/milica-skipina)

### Definicija problema:
Autonomna vožnja vozila unutar 2D simuliranog okruženja bez automatskog zaštitnog sistema (safety sistem za automatsko kočenje), pomoću algoritma učenja uslovljavanjem u distribuiranom sistemu.
Nadovezivanje na [projekat ](https://github.com/ftn-ai-lab/ori-2021-siit/issues/28) iz predmeta ORI. Akcenat je stavljen na postizanje boljih rezultata, implementaciju _DDDQL_ algoritma (_Distributed Double Deep Q Learning_), kao i implementaciju podsistema za praćenje kvaliteta treniranja.

### Skup podataka:
Ne postoji, agent uči isključivo iz okruženja.

### Okruženje:
Reč je o custom implementaciji 2D okruženja saobraćaja na auto putu. Okruženje se sastoji iz 2 dela: servera koji diktira dinamiku saobraćaja i komunicira sa sistemom za donošenje odluka (agentovom mrežom), i web aplikacije koja prikazuje trenutno stanje svih instanci okruženja u browser-u. Komunikacija  se odvija preko WebSocket protokola. U okviru implementacije okruženja se takođe nalazi logika za davanje povratne informacije mreži za svrhe treniranja (nagrade ili kazne za svaku donetu odluku).

### Metodologija:
Procesi eksploracije i učenja su odvojeni, odnosno nezavisni. Inicijalno kreiraju se 2 mreže sa nasumičnim parametrima (Q i Target mreže). Agent vrši upit ka target mreži u određenoj frekvenciji i dobija odgovor koju akciju treba da izvrši. Akcija se sastoji iz 2 dela, da li da skrene levo, desno ili ostane u trenutnoj traci, kao i to da li da ubrza ili uspori. U početku, odluke se donose nasumično, korišćenjem _epsilon greedy policy_ algoritma. Okruženje vraća sistemu za odlučivanje ocenu svake odluke i na osnovu toga agent uspeva da uči. Ideja je da se ovo odvija u distribuiranom sistemu tako da se hardverska ograničenja mogu lakše prevazići i da se proces treniranja može lakše skalirati. U tom kontekstu, postojale bi instance generatora gradijenata od kojih bi svaka generisala gradijent na osnovu istorjie odluka (i ocena) i slala gradijent orkestratoru. Orkestrator bi preuzeo odgovornost primenjivanja gradijenta na Q mrežu, kao i povremene sinhronizacije Target i Q mreže. Nakon svake epizode, okruženje bi slalo rezultat agenta na API koji prikuplja podatke treninga. Cilj je implementirati mehanizam za jednostavan pregled i poređenje rezultata treniranja za različite konfiguracione parametre, što bi ubrzalo proces optimizacije tih parametara.

### Fokus:
1. Implementacija distriburianog RL algoritma.
2. Implementacija mehanizma za evaluaciju kvaliteta treniranja.
3. Optimizovanje konfiguracionih parametara i, kao rezultat toga, poboljšanje kvaliteta treniranja.

### Evaluacija:
Poređenje dobijenih rezultata sa rezultatima dobijenim do sada. Kvalitet učenja, odnosno provera da li agent postepeno ili naglo uči/zaboravlja.
U kontekstu distribuiranog sistema, rešenje je kvalitetno ako skaliranje ne zahteva veliki trud i vreme, a daje bolje rezultate treniranja.
Mehanizam evaluacije kvaliteta treniranja je dobar ukoliko je moguće brzo doneti odluku o tome da li je određena konfiguracija bolja od prethodne ili neke druge.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by bjelicaluka** [comment]
https://github.com/bjelicaluka/self-driving-rl
