### ISSUE TITLE
Autonomna vožnja modela (igračke) automobila

### ISSUE THREAD

**Issue by nedeljkovignjevic** [ftn-ai-lab/sc-2021-siit#24]
## Tim:
- Nedeljko Vignjević SW-59/2018
- Dejan Todorović SW-17/2018

## Asistenti:
- Dragan Vidaković
- Milica Škipina

## Definicija problema:
Obučiti model automobila da se kreće po napravljenoj stazi uz prepoznavanje saobraćajnih znakova. 
Osnova modela automobila je šasija sa 4 motora. Model je kontrolisan pomoću ESP32 čipa.

![spot](https://user-images.githubusercontent.com/54076398/147362676-40697f67-570a-4582-8c77-82583127d6d8.jpeg)

## Skup podataka:
Skup podataka će biti ručno kreiran i sadržaće video materijal vožnje modela automobila nad napravljenom stazom.
Video materijal će biti kreiran uz pomoć OV7670 kamera modula prikačenog na model automobila.

## Metodologija:
Ideja je da se kreira jedna "backbone" neuronska mreža koja bi služila kao podrška odvojenim modulima za segmentaciju puta i detekciju saobraćajnih znakova koji bi bili zasnovani na konvolucionim neuronskim mrežama.
Izlaz iz pomenutih modula bi bio ulaz u modul za planiranje koji bi trebalo da vrati vrednosti za brzinu i ugao skretanja. 
Model će biti obučavan end to end, ali biće moguće i keširanje feature-a koje je izdvojila backbone neuronska mreža tako da se gore pomenuti moduli mogu dotrenirati odvojeno. 

## Evaluacija:
- Kao mera performanse za detekciju saobraćajnih znakova koristiće se F mera.
- Ponašanje modela automobila po napravljenoj stazi biće evaluirano empirijski.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by nedeljkovignjevic** [comment]
Link ka github repozitorijumu projekta: https://github.com/nedeljkovignjevic/spot
