### ISSUE TITLE
Detekcija postojanja zaštitnog šlema i njegove boje na glavama radnika

### ISSUE THREAD

**Issue by nadjagv** [ftn-ai-lab/sc-2021-siit#25]
**Tim**
Matija Pojatar SW 11/2018
Nađa Gvozdenac SW 10/2018

**Asistent**
Dragan Vidaković

**Definicija problema**
Cilj projekta je detekcija postojanja zaštitnog šlema i njegove boje na glavama radnika na slici. Ulaz su fotografije na kojima neki radnici nose šlem, neki ne, a izlaz označavanje šlemova po njihovoj boji i radnika koji ne nose šlemove.

**Skup podataka**
Koristiće se skup podataka sa [ovog linka](https://www.kaggle.com/abhishek4273/helmet-dataset) za treniranje, dok ćemo sami formirati test skup.

**Metodologija**
Koristiće se SSD (Single shot detection) za detekciju objekata na fotografijama, a za klasifikaciju će se koristiti DNN (Deep Neural Network) i Haar-Cascade koje ćemo uporediti.

**Evaluacija**
Skup podataka ćemo podeliti na trening i test podatke.  Za evaluaciju će se koristiti accuracy loss. Posmatraće se broj tačno prepoznatih slučajeva nošenja šlema kao i njegova boja.

**Repozitorijum**
Link do repozitorijuma: https://github.com/nadjagv/helmet-detect.git

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by nadjagv** [comment]
Hvala! Repozitorijum: https://github.com/nadjagv/helmet-detect.git
