### ISSUE TITLE
Graph Attention Network za kontekstnu detekciju objekata

### ISSUE THREAD

**Issue by njmarko** [ftn-ai-lab/sc-2021-siit#28]
# Članovi tima
Ime i prezime | Broj indeksa | Grupa
------------ | ------------- | -------------
[Marko Njegomir](https://github.com/njmarko) | SW-38/2018 | 1
[Dušan Erdeljan](https://github.com/dusanerdeljan) | SW-43/2018 | 1

# Asistent
[Dragan Vidaković](https://github.com/vdragan1993)

# Definicija problema
Većina algoritama za detekciju objekata razmatra regije sa slike individualno bez uzimanja celokupnog konteksta scene. Intuicija je da se neki objekti često pojavljuju u scenama zajedno sa određenim objektima ili se pojavljuju u grupama. Ideja je da napravimo Graph Attention Network (GAT) model koji će, prilikom predikcije, uzeti prostorne i semantičke veze između objekata na slici u obzir i na taj način poboljšati predikciju modela.

# Skup podataka
Koristićemo COCO dataset (https://cocodataset.org/#home, https://arxiv.org/pdf/1405.0312.pdf) za detekciju objekata.

# Metodologoija
Iz modela za object detection (pretrenirani Faster R-CNN) će se uzeti region of interest (ROI) embedinzi i na osnovu njih će se konstruisati graf koji modeluje scenu. Na graf će se primeniti Graph Attention Network model čiji će izlaz biti modifikovani embedinzi. Nad modifikovanim embedinzima će se vršiti klasifikacija i određivanje bounding box-ova.

# Evaluacija
Koristićemo mAP (Mean Average precision) i AP across scales (za male, srednje i velike objekte).
Više informacija o metrikama se može pronaći na sledećem linku: https://cocodataset.org/#detection-eval.

# Repozitorijum

https://github.com/njmarko/gat-or

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
