### ISSUE TITLE
Prepoznavanje hrane i računanje kalorija

### ISSUE THREAD

**Issue by FickosOP** [ftn-ai-lab/sc-2021-siit#29]
**1. Tim**
  Filip Volarić SW54-2018
  Svetozar Vulin SW57-2018

**2. Asistent**
  Milica Škipina

**3. Definicija problema**
  Potrebno je sa slike prepoznati namirnice, a zatim sračunati broj kalorija svake namirnice.

**4. Motivacija problema**
  Jednostavno dobijena informacija o količini kalorija koju osoba unosi određenim obrokom.

**5. Skup podataka**
  Skup će biti preuzet sa [linka](https://www.dropbox.com/sh/3sp4gd271jwdyxr/AABk0npNIzyysjTPtRHwEbySa?dl=0). U skupu postoji poseban folder za svaku namirnicu.

**6. Metodologija**
  Za izdvajanje namirnice sa slike, računanje zapremine i kalorijske vrednosti svake pojedinačne namirnice koristićemo sledeće metode:

- Canny edge detector
- Watershed segmentation
- Otsu's method

 Zapreminu hrane planiramo da računamo poređenjem sa dimenzijama palca koji se nalazi pored tanjira na svakoj slici u skupu. Nakon računanja zapremine, masu dobijamo pomoću tabele gustine.
  
 Feature vector ćemo dobiti koristeći HSV za boju, Gabor filter za teksturu, hu moments za oblik.
  
 Za klasifikaciju ćemo koristiti SVM.

**7. Evaluacija**
  Skup podataka ćemo podeliti tako da ćemo 80% iskoristiti za trening a 20% za test skup.
  Preciznost za klasifikaciju namirnica.

**Comment by milica-skipina** [comment]
Korigujte link ka skupu podataka.

**Comment by FickosOP** [comment]
> Korigujte link ka skupu podataka.

Ispravljeno.

**Comment by milica-skipina** [comment]
U kojem skupu podataka se pored tanjira nalazi palac?

**Comment by FickosOP** [comment]
To je jedan od načina za kalibraciju koji smo pronašli na internetu, da li je u redu da izmenimo to, pa da iskoristimo ovaj skup podataka koji smo naveli.

**Comment by milica-skipina** [comment]
Opišite detaljnije postupak određivanja zapremine hrane. Da li će se koristiti slike na kojima se već nalazi palac pored tanjira ili je u pitanju drugačiji pristup?

**Comment by FickosOP** [comment]
Pronašli smo odgovarajući skup. Sada možemo da koristimo navedeni postupak.

**Comment by milica-skipina** [comment]
Proširite evaluaciju tako što ćete definisati metriku za izračunati broj kalorija.

Za maksimalnu ocjenu potrebno je da u test skupu podataka budu i fotografije na kojima se nalazi više različitih namirnica. Da li je to u redu?
