### ISSUE TITLE
Detekcija i klasifikacija košarkaške lopte i igrača

### ISSUE THREAD

**Issue by markuza99** [ftn-ai-lab/sc-2021-siit#3]
### Tim:

- Marković Petar - SW73/2018
- Mateja Ćosović - SW9/2018

### Asistent:
- Vidaković Dragan

### Definicija problema:
Detekcija i klasifikacija košarkaške lopte i igrača na košarkaškoj utakmici upotrebom odgovarajućih YOLO algoritama.

### Skup podataka:
Za trening podatke ćemo koristiti isečke sa košarkaških utakmica i praviti naš custom dataset, labelovanjem igrača i lopte. Test podaci bi takođe bili isečci košarkaških utakmica.

### Metodologija:
- YOLOv3
- YOLOV3-tiny
- YOLOv4
- YOLOv4-tiny

### Evaluacija:
Kao metriku za merenje performansi iskoristićemo preciznost i tačnost nad testnim podacima.

**Comment by vdragan1993** [comment]
Da li će modeli navedeni u metodologiji biti ručno implementirani, ili će se koristiti gotovi?

Da li se evaluacija odnosi na kompletan problem, ili samo njegov određeni deo (npr. klasifikaciju)?

**Comment by markuza99** [comment]
Pozdrav,

Za sada je ideja da koristimo gotove modele.

Što se evaluacije tiče, verovatno bismo koristili mAP funkciju za testiranje modela.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by markuza99** [comment]
https://github.com/markuza99/YOLO-Basketball-Object-Detection-And-Tracking
