### ISSUE TITLE
Virtuelno crtanje u realnom vremenu

### ISSUE THREAD

**Issue by albertmakan** [ftn-ai-lab/sc-2021-siit#30]
## Članovi tima:
- [Albert Makan](https://github.com/albertmakan) (SW-29/2018)
- [Laslo Sabadi Baranji](https://github.com/Lakiprog) (SW-51/2018)

## Asistent:
- Dragan Vidaković

## Definicija problema:
Virtuelno crtanje na sliku kamere u realnom vremenu sa pokretima šake i prstiju.
Potrebno je detektovati ruke i prepoznati određene akcije.
Inicijalno biće podržane sledeće akcije: crtanje, brisanje, menjanje boje, selekcija i premeštanje objekta.
Nacrtani objekti će biti korigovani, to jest zamenjeni pravilnom oblikom iste veličine ako su blizu pravilnog oblika.
Biće podržana korekcija linije, trougla, pravougaonika i elipse.

## Skup podataka:
Skup podataka za klasifikaciju pokreta ruke ćemo sami konstruisati. Sadržaće kratke video snimke zajedno sa labelama (najverovatnije u imenu fajla). Po potrebi podaci biće i augmentirani. 

## Metodologija:
Za detekciju ruke i _hand landmarks_ planiramo da koristimo MediaPipe biblioteku.
Za klasifikaciju pokreta ruku sami implementiramo konvolucionu neuronsku mrežu.
Za prepoznavanje nacrtanih objekata u cilju njihove potencijalne korekcije, koristićemo OpenCV metode.

## Evaluacija:
Skup podataka će biti podeljen na trening i validacioni skup u odnosu 85:15. Za evaluaciju ćemo koristiti _accuracy_. Takođe ćemo koristiti i _user experience_ odnosno lakoću korišćenja kao empirijsku metriku.

## Repozitorijum:
https://github.com/albertmakan/virtual-paint

**Comment by vdragan1993** [comment]
Da li će se crtanje izvoditi u sklopu nekog programa (npr. Paint ili Photoshop)?
Crtanje kojih objekata će biti podržano i kako će se vršiti njihova korekcija ako su blizu pravilnog oblika?
Da li će se `user experience` meriti empirijski ili uz pomoć neke metrike (ili više njih)?

**Comment by albertmakan** [comment]
Crtanje nećemo izvoditi u sklopu nekog programa, nego u "vazduhu".
Korigovali smo definiciju problema i evaluaciju tako što smo dali odgovore na postavljena pitanja.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
