### ISSUE TITLE
Detekcija automobila na videu, detekcija tablica na automobilu i obrada tablica

### ISSUE THREAD

**Issue by isidora-stanic** [ftn-ai-lab/sc-2021-siit#31]
### Tim
Jovana Klimenta SW-1-2018
Matija Matović SW-6-2018
Isidora Stanić SW-16-2018

### Asistent
Milica Škipina
Dragan Vidaković

### Definicija problema
Detekcija automobila na videu, detekcija tablica na automobilu i obrada tablica

### Skup podataka
Za detekciju automobila:
[Stanford cars dataset](http://ai.stanford.edu/~jkrause/cars/car_dataset.html)
Za detekciju tablica:
[Car Licence Plate Detection](https://www.kaggle.com/andrewmvd/car-plate-detection)
Za detekciju tablica i vozila:
[License Plates Dataset](https://public.roboflow.com/object-detection/license-plates-us-eu)
Rešenje ćemo testirati na snimcima koje mi budemo sami snimili

### Metodologija
YOLO v3/ YOLO v3-tiny za detekciju automobila. Model ćemo sami implementirati i trenirati na skupovima podataka
Hough za određivanje granica tablice
HOG + Canny + SVM za obradu tablice (određivanje slova i brojeva)

### Evaluacija
Proveravaćemo accuracy na slikama iz skupova podataka s obzirom da skupovi podataka već sadrže testne podatke.
Za evaluaciju detekcije vozila i tablica će se koristiti precision, f-score i recall. Za lokalizaciju mean average precision.
Kompletno rešenje ćemo empirijski testirati na video snimcima koje mi budemo snimili.

### Repozitorijum
https://github.com/JolaKl/soft_kompjuting

**Comment by milica-skipina** [comment]
U definiciji problema je navedeno da će se detekcija automobila vršiti na videu, dok navedeni skupovi podataka sadrže samo slike. Korigujte prijavu tako što ćete navesti koje video snimke planirate da koristite. 

Da li će model YOLO v3 biti ručno implementiran, ili ćete koristiti gotov?

Zamolila bih vas da preciznije opišete kako planirate da evaluirate rezultate.

**Comment by MatijaMatovic** [comment]
Koristili bi smo neku pre-treniranu implementaciju YOLOv3, s obzirom na to da treniranje traje dugo. Posle bi smo nju tweak-ovali i prilagodili nasem skupu podataka, Ukoliko je potrebno, mozemo napraviti i nasu implementaciju YOLOv3 modela. Takodje, da li bi bilo u redu da umesto na videu, prepoznajemo sa fotografija? Tojest, detekcija automobila (njegove marke i godista, ukoliko sama detekcija automobila ne zadovoljava obim projekta za 3 osobe) i tablica na fotografiji (tekst na njima)? U tom slucaju evaluacija rezultata je prilicno jednostavna, a i sve bi bilo u skladu sa datim skupovima podataka.

**Comment by isidora-stanic** [comment]
Poštovani, izmenili smo issue prema sugestijama. Molimo vas da pogledate da li je sve u redu.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by isidora-stanic** [comment]
Poštovani, dodat je link ka privatnom repozitorijumu
