### ISSUE TITLE
Detekcija i klasifikacija riba

### ISSUE THREAD

**Issue by LeeVanCleef-dotcom** [ftn-ai-lab/sc-2021-siit#32]
### **Tim:**
- Stefan Baćić SW68-2018

### **Asistent:**
- Dragan Vidaković

### **Repo:**
https://github.com/LeeVanCleef-dotcom/soft-computing-fish-classification-project 

### **Definicija problema:**
Obučiti model da na osnovu slike detektuje i prepozna vrstu ribe. 

### **Skup podataka:**
Koristiće se skup podataka sa kaggle.com: 
- https://www.kaggle.com/crowww/a-large-scale-fish-dataset
Skup podrazumeva 9 sledećih morskih vrsta: Black Sea Sprat (papalina), Gilt-Head Bream (orada), Horse Mackerel (skuša), Red Mullet (barbun), Red Seabream (crvena orada), Sea Bass (brancin), Shrimp (škampi), Striped Red Mullet (prugasti barbun), Trout (pastrmka). 
Ulazni skup podataka podeljen je na 1000:50 (trening:test).

### **Metodologija:**
Kreirati i obučiti custom CNN model za klasifikaciju. Za detekciju će se koristiti sliding box tehnika za detekciju objekata.

### **Evaluacija:**
Što se tiče evaluacije klasifikacije biće korišćena accuracy, a za evaluaciju detekcije IoU metrika.

**Comment by vdragan1993** [comment]
Prepoznavanje koliko i kojih vrsta riba će biti podržano?
Da li će se custom CNN modelom biti vršena i detekcija, ili će se za to koristiti nešto drugo?
Koje sve metrike će biti računate prilikom evaluacije rešenja?

**Comment by LeeVanCleef-dotcom** [comment]
Ukoliko uspem da oformim sopstveni skup podataka biće podržano prepoznavanje 6 "domaćih" ribljih vrsta (bandar, štuka, smuđ, bucov, som, sunčica), a ukoliko ne, onda svih 9 vrsta sa linka navedenog gore. 
Što se tiče detekcije nisam još uvek odredio da li će biti vršena CNN modelom ili sliding box metodom (verovatno drugo).
Metrika za merenje performansi modela biće tačnost i preciznost istog nad testnim podacima.

**Comment by vdragan1993** [comment]
Prethodnim odgovorom je neodređenost ovog projekta dodatno povećana. 
Potreno je da se ta neodređenost smanji i projekat preciznije definiše.

Neophodno je da se odlučite i da precizirate broj i same vrste riba čije će prepoznavanje biti podržano. Na osnovu toga ćete precizirati i deo vezan za skup podataka.

Dodatno, potrebno je da proširite:
- metodologiju - tako što ćete navesti kako planirate da radite detekciju
- evaluaciju - tako što ćete precizno navesti koju/koje metriku/metrike planirate da koristite za evaluaciju detekcije, a koju/koje za evaluaciju klasifikacije.

**Comment by LeeVanCleef-dotcom** [comment]
Ja se izvinjavam, mislio sam da je fleksibilnost u ovoj fazi specifikacije donekle postojeća. 
U tom slučaju koristiću skup podataka sa kaggle.com naveden gore i time podrazumevam 9 sledećih morskih vrsta: Black Sea Sprat (papalina), Gilt-Head Bream (orada), Horse Mackerel (skuša), Red Mullet (barbun), Red Seabream (crvena orada), Sea Bass (brancin), Shrimp (škampi), Striped Red Mullet (prugasti barbun), Trout (pastrmka).
Ulazni skup podataka podeljen je na 1000:50 (trening:test).
Detekcija će biti vršena pomoću sliding box tehnike za prepoznavanje objekata. 
I na kraju što se tiče evaluacije klasifikacije biće korišćena accuracy, a za evaluaciju detekcije IoU metrika.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
