### ISSUE TITLE
Detekcija gestikulacije ruke

### ISSUE THREAD

**Issue by JovanovicAca** [ftn-ai-lab/sc-2021-siit#34]
**Tim**
Aleksandar Jovanović sw78/2018

**Asistent**
Vidaković Dragan

**Definicija problema**
Prepoznavanje znakova rukom pomoću porodice YOLO algoritama.

**Skup podataka**
Skup podataka je https://www.kaggle.com/gti-upm/leapgestrecog

**Metodologija** 
Koristiće se YOLOv3.

**Evaluacija**
Dataset će biti podeljen na test i trening skup u odnosu 80:20. Preciznost će se meriti na osnovu rezultata mAP funckije.

**Link repozitorijuma**
https://github.com/JovanovicAca/HandGesticulate

**Comment by vdragan1993** [comment]
Prepoznavanje koliko i kojih znakova će biti podržano?
Da li će se vršiti prepoznavanje sa slike, videa ili real-time?
Da li će model naveden u metodologiji biti ručno implementiran, ili će se iskoristiti gotov?

**Comment by JovanovicAca** [comment]
Biće podržano prepoznavanje 10 znakova (pesnica, palac, znak ok rukom itd.)
Vršiće se prepoznavanje sa slike.
Biće korišćen gotov model.

**Comment by vdragan1993** [comment]
Navedite sve znakove čije će prepoznavanje biti podržano.

**Comment by JovanovicAca** [comment]
1. Pokazivanje dlana (prednja strana, svi prsti se vide)
2. Znak L rukom (ispruženi palac i kažiprst, ostali prsti skupljeni)
3. Stegnuta pesnica (sa prednje strane, gde se vide prsti)
4. Stegnuta pesnica (gledano sa druge strane, sa strane gde se vidi mali prst)
5. Pokazivanje palca
6. Pokazivanje kažiprsta
7. Pokazivanje znaka OK (kažiprst dodiruje palac)
8. Dlan (gledano sa strane malog prsta)
9. Pokazivanje slova C, savijena šaka
10. Šaka prikazana odozdo

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
