### ISSUE TITLE
Detekcija i rešavanje osmosmerke

### ISSUE THREAD

**Issue by jovandjordjic** [ftn-ai-lab/sc-2021-siit#36]
<h2>Tim</h2>

- Milica Jovović, SW-15/2018
- Jovan Đorđić, SW-46/2018

Link ka repozitorijumu: [Link](https://github.com/jovandjordjic/soft-kompjuting)

<h2>Asistenti</h2>

- Milica Škipina
- Dragan Vidaković

<h2>Definicija problema</h2>
Na osnovu učitane slike, vrši se detekcija zadatih reči i osmosmerke, kao i rešavanje same osmosmerke.

<h2>Skup podataka</h2>
Podatke ćemo generisati na osnovu osmosmerki datih na <a href="https://www.enigmatika.rs/ukrstenice/osmosmerke/">linku</a>. Skup podataka će biti kreiran parsiranjem podataka u interni format koji će sadržati slike osmosmerki koje treba rešiti, uz koje će biti pripisano i konačno rešenje puzle.

<h2>Metodologija</h2>

- Pretprocesiranje slike
- Detekcija zadatih reči i slova u osmosmerci (OCR)
- Detekcija grida osmosmerke
- Rešavanje osmosmerke na osnovu implementiranog algoritma (posmatranje dužine reči i slova od početnog do krajnjeg) 
- Prikaz i analiza dobijenog rešenja

<h2>Evaluacija</h2>
Za evaluaciju rešenja će se koristiti accuracy. Prvo se proverava da li su sva slova pravilno prepoznata, a onda i da li je rešenje osmosmerke ispravno.

**Comment by milica-skipina** [comment]
Za najveću ocenu, predlažemo da proširite skup podataka tako što ćete dodati slike osmosmerki uslikane telefonom pod različitim uglovima i nivoom osvjetljenja.
Da li je to u redu?

**Comment by jovandjordjic** [comment]
Naravno, odgovara nam.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by jovandjordjic** [comment]
Dodat link ka repozitorijumu, hvala.
