### ISSUE TITLE
Detekcija i prepoznavanje saobraćajnih znakova sa slike

### ISSUE THREAD

**Issue by UrosPsd** [ftn-ai-lab/sc-2021-siit#37]
# Detekcija i prepoznavanje saobraćajnih znakova sa slike

## **Članovi tima:**

- Uroš Petrić, SW61-2018

## **Asistent:**
Milica Škipina

## **Repozitorijum:**
https://github.com/UrosPsd/trafficio

## **Definicija problema:**
Prepoznavanje i klasifikacija saobraćajnih znakova sa slike pomoću neuronskih mreža.

## **Motivacija problema:**
Prepoznavanje i klasifikacija saobraćajnih znakova je veoma važan zadatak za sve automobile koji imaju mogućnost autopilota ne bi li uspevali da ispoštuju sva pravila saobraćaja na putu.

## **Skup podataka:**
Za potrebu projekta koristiće se skup od **50,000** slika različitih saobraćajnih znakova podeljenih u **43** različite klase.
Dataset se može pronaći na ovom [linku](https://www.kaggle.com/meowmeowmeowmeowmeow/gtsrb-german-traffic-sign).

## **Metodologija:**
Za izradu rešenja koristićemo sledeće algoritme i biblioteke:

**CNN** - detekcija i klasifikacija
**Keras** - čuvanje istreniranog modela
**Matplotilib** - iscrtavanje grafa preciznosti i gubitka
**Pandas** - čitanje csv file-a i povezivanje slika sa opisom
**PIL biblioteka** - pretvaranje slike u niz

## **Evaluacija:**
Pronadjeni dataset već sadrži test folder što predstavlja 10% ukupnog dataseta. Trening skup će biti 80% a validacioni 10%.
IoU (_Intersection over Union_) će se koristiti kao metrika za detekciju saobraćajnih znakova dok će evaluacija biti grafički prikazana preko Matplotlib biblioteke i predstavljaće procenat tačno prepoznatih znakova.

**Comment by milica-skipina** [comment]
Projekat nema dovoljnu složenost za tim od dva člana.
Predlažem da korigujete prijavu tako što će se detekcija i prepoznavanje saobraćajnih znakova raditi na fotografijama koje imaju širi kontekst (fotografije sa ulica i/ili autoputa). Da li je to u redu?

**Comment by UrosPsd** [comment]
U redu je. Našli smo novi dataset koji u sebi ima i fotografije koje ste predložili. Jel to sada odgovara?

**Comment by Toscanello** [comment]
Izdvajaćemo više znakova sa slike ulice, i vršiti njihovu klasifikaciju.

Ivan Luburić

**Comment by milica-skipina** [comment]
Korigujte opis skupa podataka da odgovara novom.
Proširite evaluaciju tako što ćete definisati i metriku za detekciju saobraćajnih znakova.

**Comment by UrosPsd** [comment]
Kolega Ivan i ja samo u medjuvremenu shvatili da dataset koji smo naknadno našli nije najbolji za ovaj zadatak. Da li je u redu da samo ja odradim projekat koji sam opisao u issue a Ivan će kreirati novi koji će sam uraditi?

**Comment by milica-skipina** [comment]
Još uvijek je potrebno da proširite evaluaciju tako što ćete definisati i metriku za detekciju saobraćajnih znakova.
U naredna 24 sata, ili dopunite evaluaciju, ili prijavite predefinisani projekat.

**Comment by UrosPsd** [comment]
Ispravio sam specifikaciju. Nadam se da ste na to mislili.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
