### ISSUE TITLE
Praćenje pozicije lopte na video snimku

### ISSUE THREAD

**Issue by marko16** [ftn-ai-lab/sc-2021-siit#38]
# Autor projekta
- Marko Šuljak, SW-35/2018

# Asistent
- Dragan Vidaković

# Definicija problema
- Zadatak projekta je detekcija lopte na video snimku (koji se beleži live preko kamere laptopa) i praćenje njene pozicije na snimku u real-time.

# Metodologija
- Sama detekcija pozicije lopte na frame-u video snimka biće realizovana uz pomoć procesuiranja slike. Ovaj proces podrazumeva pronalaženje granica lopte i njene boje korišćenjem OpenCV biblioteke. 
- Lokacija lopte na svakom od frame-ova biće beležena u listu kao torka koordinata lopte (x, y). Ovo je potrebno da bi mogli da vizualizujemo detekciju lokacije lopte po frame-ovima i prikazivanje "traga" (pozicije lopte u proteklim frame-ovima).

# Evaluacija 
- Evaluacija samih performansa softvera biće empirijska jer je jednostavno uočiti obeležene granice lopte na slici i liniju koja predstavlja njen trag.

**Comment by vdragan1993** [comment]
Koja lopta će biti detektovana i praćena?

**Comment by marko16** [comment]
Planirao sam da lopta bude jednobojna i obicna ali ako to nije dovoljno mogu dodati i prepoznavanje bilo koje vrste lopte preko npr Resnet neuronske mreže.

**Comment by vdragan1993** [comment]
Pošto radite sami, možete da radite bez prepoznavanja vrste lopte.

Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by marko16** [comment]
Link ka github repozitorijumu projekta: https://github.com/marko16/ball_detection_and_tracking
