### ISSUE TITLE
Generisanje muzike za igrice na osnovu slike igrice

### ISSUE THREAD

**Issue by rajtarovN** [ftn-ai-lab/sc-2021-siit#4]
Tim:

    Dragan Arsic - SW-5/2018
    Natasa Rajtarov - SW-2/2018

Asistent:

    Vidaković Dragan

Definicija problema:

Generisanje muzike za igrice na osnovu slike igrice. Muzika se generise u formatu MIDI file-a

Dataset:

koristice se muzika sa sledeceg linka https://www.vgmusic.com/
Na datom linku postoji preko 33000 MIDI file-ova koji ce se koristiti za treniranje mreza.
Slike koje ce se asocirati sa muzikom nabavljene su vrsenjem google pretrage naziva pesme i igrice iz koje je, takodje i pretragom http://www.honestgamers.com/assets/2464/view/0.html i https://www.giantbomb.com/the-magical-quest-starring-mickey-mouse/3030-1922/images/ koji daju uglavnom bolje rezultate od google-a za starije igrice.

Arhitektura:

    Resenje se sastoji iz dve neuronske mreze. Prva neuronska mreza na osnovu boja slike generise pocetan MIDI file koji druga neuronska mreza GPT-2 koristi za input i na osnovu tog file-a generise pesmu.

    Za GPT-2 mrezu ce biti fork-ovan fork GPT-2 mreze https://github.com/nshepperd/gpt-2 uz nase izmene.

Evaluacija:

Evaluacija ce biti vrsena kvalitativno

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by rajtarovN** [comment]
https://github.com/Blizzsuxx/MusicGenerator github repozitorijum
