### ISSUE TITLE
Real-time detekcija i klasifikacija osoba po kategoriji socijalne distance na video-snimku 

### ISSUE THREAD

**Issue by dovvla** [ftn-ai-lab/sc-2021-siit#42]
### Tim
Vladimir Jovin SW-30/2018
Jovan Petljanski SW-31/2018
Milovan Milovanović SW-41/2018

### Asistent
Dragan Vidaković

### Definicija problema
Potrebno je prepoznati osobe u datom frejmu video-snimka u realnom vremenu i klasifikovati svaku od njih u jednu od sledeće tri kategorije socijalne distance: bezbedno, potencijalno rizično, rizično.

### Skup podataka
Koristiće se prethodno trenirani modeli (COCO skup podataka), a za potrebe testiranja će biti upotrebljen skup podataka sa [linka](https://academictorrents.com/details/35e83806d9362a57be736f370c821960eb2f2a01).

### Metodologija
Za detekciju osoba na snimku koristiće se sledeće arhitekture:

- YOLOv4
- YOLOv4-tiny (zbog pogodnosti rada u realnom vremenu)
- SSD (Single-Shot Detector)
- potencijalno drugi modeli

Svaka detektovana osoba biće asocirana sa trojkom _(x, y, d)_, gde su _x_ i _y_ koordinate centroida, a _d_ je dubina u odnosu na poziciju kamere. Na osnovu ovoga biće formirana matrica razdaljine pomoću koje će se određivati međusobna udaljenost. Prag blizine će biti dinamički određivan.

### Evaluacija
Za evaluiranje detekcije osoba koristiće se mAP (mean Average Precision).
Za evaluiranje performansi koristiće se odnos mAP-a i FPS-a (broj frejmova koji se mogu obraditi u sekundi).
Rezultati pojedinačnih arhitektura će se međusobno porediti.

### Repozitorijum
https://github.com/Dovla999/social-distancing

**Comment by vdragan1993** [comment]
Šta određuje svaku od kategorija socijalne distance?

**Comment by dovvla** [comment]
Kategorija socijalne distance osobe će zavisiti od njene udaljenosti od drugih osoba u datom frejmu. Ukoliko je osoba minimalno 3 metra udaljena od svake druge osobe u frejmu, ta osoba pripada kategoriji "bezbedno". Ukoliko je ta udaljenost između 2 i 3 metra biće "potencijalno rizično", a u slučaju da je udaljenost manja od 2 metra biće "rizično".

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
