### ISSUE TITLE
Prepoznavanje bolida formule 1

### ISSUE THREAD

**Issue by Mladenv7** [ftn-ai-lab/sc-2021-siit#43]
### Članovi tima:
Ivan Čolak, SW23-2013
Mladen Vasić, SW28-2018

### Asistenti:
Dragan Vidaković
Milica Škripina

### Definicija problema:
Prepoznavanje bolida formule 1

### Skup podataka: 
Ručno prikupljeni klipovi sa Youtube-a i slike bolida

### Metodologija:
Koristićemo YOLO algoritam.

### Evaluacija:
Za evaluaciju će se koristiti _accuracy_.

**Comment by vdragan1993** [comment]
Iz predloga nije jasan opis cilja projekta, kao i opis plana realizacije tog cilja.
Predlog se zbog velikog broja nedostataka odbija.
U naredna 24h prijavite predefinisane projekte.
