### ISSUE TITLE
Detekcija raspoloženja osobe

### ISSUE THREAD

**Issue by svetaa99** [ftn-ai-lab/sc-2021-siit#46]
Tim
Vulin Svetozar SW-57-2018

Asistent
Škipina Milica

Definicija problema
Detekcija lica osobe sa slike ili videa, prepoznavanje raspoloženja na osnovu facijalne ekspresije kod te osobe i kreiranje odgovarajućeg emoji-a na osnovu prepoznatog raspoloženja. Moguće je prepoznati sledeća raspoloženja: 
  - Bes
  - Gađenje
  - Strah
  - Sreća
  - Tuga
  - Iznenađenost
  - Neutralno

Skup podataka
Skup podataka se nalazi na linku: https://www.kaggle.com/msambare/fer2013

Metodologija
Treniranje custom CNN-a sa podacima
Koristiće se openCV haar cascade xml da bi se nacrtao bounding-box oko face osobe sa kamere i zatim se taj box šalje do CNN mreže koja služi za prepoznavanje i klasifikaciju raspoloženja.
Kao output CNN daje prepoznato raspoloženje i korišćenjem openCV se generiše odgovarajući emoji.

Evaluacija
Dataset će biti podeljen na trening i test podatke, koji će biti u odnosu 85:15. Ti podaci će biti korišćeni za obučavanje custom CNN mreže. Za evaluaciju će se koristiti preciznost prepoznatih ekspresija. IoU će biti korišćen za evaluaciju detekcije. Prilikom live detekcije, biće beleženi rezultati i tačnost prepoznatih ekspresija.

**Comment by milica-skipina** [comment]
Projekat nema dovoljnu složenost za najveću ocjenu.
U naredna 24 sata korigujte prijavu ili prijavite predefinisani projekat.

**Comment by svetaa99** [comment]
Ispravio sam specifikaciju sada

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by svetaa99** [comment]
Hvala!
Link ka repozitorijumu: https://github.com/svetaa99/emojifoni
