### ISSUE TITLE
Predefinisani projekat 3

### ISSUE THREAD

**Issue by Toscanello** [ftn-ai-lab/sc-2021-siit#47]
# Student
Ivan Luburić sw-13-2018

# Asistent
Milica Škipina

# Metodologija
Thresholding za razdvajanje kuglica.
Canny Edge za detekciju ivica.

# Repozitorijum
https://github.com/Toscanello/soft

**Comment by milica-skipina** [comment]
Potrebno je da proširite evaluaciju tako što ćete definisati i metriku za detekciju biljaka.
U naredna 24 sata, ili dopunite evaluaciju, ili prijavite predefinisani projekat.

**Comment by Toscanello** [comment]
Promenio sam ipak ću raditi predefinisani.
