### ISSUE TITLE
Detekcija i klasifikacija životinja

### ISSUE THREAD

**Issue by jelenamiletic** [ftn-ai-lab/sc-2021-siit#5]
## Tim

Daniel Božanić SW-63/2018
Nenad Petković SW-37/2018
Jelena Miletić  SW-45/2018

## Asistenti

Milica Škipina
Vidaković Dragan

## Definicija problema

Detekcija i klasifikacija životinja ('bird', 'cat', 'dog', 'elephant', 'zebra', 'giraffe') na slici i videu.

## Skup podataka

YOLO modeli koje ćemo koristiti su već trenirani na [_COCO skupu podataka_ ](https://github.com/pjreddie/darknet/blob/master/data/coco.names).
Modeli će biti testirani nad slikama i videima. Podaci za testiranje će biti ručno prikupljani i anotirani.  

## Metodologija

- YOLOv3
- YOLOV3-tiny
- YOLOv4
- YOLOv4-tiny

Težine i konfiguracije za ove YOLO modele ćemo odrediti eksperimentalnim putem.

## Evaluacija
Performanse modela ćemo medjusobno porediti i evaluirati.
Kao metriku za merenje performansi modela iskoristićemo preciznost i tačnost nad testnim podacima koje budemo prikupili.

**Comment by vdragan1993** [comment]
Da li će modeli navedeni u metodologiji biti ručno implementirani, ili će se koristiti gotovi?

**Comment by jelenamiletic** [comment]
Modeli će biti ručno implementirani.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by jelenamiletic** [comment]
https://github.com/DanielBozanic/animal-detection
