### ISSUE TITLE
Detekcija grbova klubova Premijer Lige

### ISSUE THREAD

**Issue by nenadicu** [ftn-ai-lab/sc-2021-siit#6]
## Tim
Uroš Nenadić SW82/2019

## Asistent
Vidaković Dragan

## Definicija Problema
Detekcija i klasifikacija grbova klubova iz Premije Lige sa slike.

## Skup podataka
Skup podataka ću sam kreirati. Koristiću slike sa utakmica, koje ću koristiti i za treniranje i testiranje. 
Slike će biti nazivane u formatu che_1, che_2 ... (Chelsea), tako i za ostalih 9 klubova.

## Metodologija 
Hog
SVM

## Evaluacija
1. Procenat uspešnosti detekcije za određeni fudbalski klub uz oslonac na IoU.
2. Procenat uspešnosti klasifikacije svih klubova.

**Comment by vdragan1993** [comment]
Proširite evaluaciju tako da uključuje i evaluaciju koraka detekcije.

**Comment by nenadicu** [comment]
Da li je sad dobra evaluacija?

**Comment by vdragan1993** [comment]
Koja metrika će se koristiti prilikom određivanja uspešnosti detekcije?

**Comment by nenadicu** [comment]
Ispravljeno.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by nenadicu** [comment]
Github link: https://github.com/nenadicu/Soft
