### ISSUE TITLE
Detekcija i klasifikacija šahovskih figura i njihovih pozicija na šahovskoj table

### ISSUE THREAD

**Issue by nikolapetrovic1** [ftn-ai-lab/sc-2021-siit#7]
## Tim
Nikola Petrović SW-34/2018
## Asistent
Dragan Vidaković
## Definicija Problema
Detekcija i klasifikacija šahovskih figura i njihovihy pozicija na šahovskoj table.
[https://towardsdatascience.com/board-game-image-recognition-using-neural-networks-116fc876dafa](url)
## Skup podataka
https://public.roboflow.com/object-detection/chess-full/24 (+ ako pronadjem jos neki)
## Metodologija
Za detekciju i klasifikaciju samih figura – YOLO - You Only Look Once: Unified, Real-Time Object Detection
Za detekciju pozicija figura na tabli – Hough transform
## Evaluacija
Postojaće dve vrste evaluacije : 
1. Procenat tačnih prepoznatih figura
2. Procenat figura na tačnim pozicijama na tabli

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by nikolapetrovic1** [comment]
Link ka repo: https://github.com/nikolapetrovic1/soft-computing-project
