### ISSUE TITLE
Detekcija i klasifikacija zmija

### ISSUE THREAD

**Issue by oljamirilovic** [ftn-ai-lab/sc-2021-siit#8]
## Tim
Olivera Mirilovic SW-62-2018

## Asistent
Dragan Vidakovic

## Repo
[detekcija i klasifikacija zmija](https://github.com/oljamirilovic/detekcija-i-klasifikacija-zmija.git)

## Definicija problema
Na osnovu ulazne slike ce se uokviriti i naznaciti vrsta prepoznate zmije ukoliko se nalazi na slici.

## Skup podataka
[Skup podataka](https://www.kaggle.com/sameeharahman/preprocessed-snake-images) jos nije konacan. Koristice se augmentacija podataka (rotacija, flipovanje, skaliranje...) kako bi se prosirio dataset.

## Metodologija
Za klasifikaciju koristice se custom konvoluciona neuronska mreza dok ce se detekcija vrstiti upotrebom Sliding Window tehnike.

## Evaluacija:
Dataset ce biti podeljen na trening i validacioni skup u odnosu 90:10, a kao mera performansi bice koriscen accuracy i loss metrika. Tacnost detekcije ce se proveravati poredjenjem bounding box-ova (istinskih i dobijenih) koriscenjem IoU metrike.

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
