### ISSUE TITLE
Prepoznavanje i rešavanje rubikove kocke

### ISSUE THREAD

**Issue by darkotica** [ftn-ai-lab/sc-2021-siit#9]
# Tim

- Zoran Jankov, SW-8/2018
- Darko Tica, SW-22/2018
- Dalibor Malić, SW-50/2018

# Asistent

- Dragan Vidaković
- Milica Škipina

# Definicija problema

- Prepoznavanje početnog stanja rubikove kocke na osnovu snimka dobijenog sa kamere (korisnik skenira stranu po stranu kocke), a zatim rešavanje same kocke pri čemu će kao izlaz biti dat niz poteza prema [konvenvciji.](http://www.rubiksplace.com/move-notations/)

# Metodologija

- Stanje svake strane kocke će biti zaključeno uz pomoć procesiranja slike. Ovaj proces obuhvata pronalaženje ivica kocke, kao i samih kvadrata u okviru njene prikazane strane (Canny edge detection), kao i pronalaženje unutrašnjih kontura koje predstavljaju kvadrate (korišćenjem OpenCV biblioteke), a zatim i određivanje boje svakog kvadrata na osnovu threshold-a boje.
- Rešavanje kocke se zasniva na neuronskoj mreži koja služi kao heuristika trenutnog stanja (udaljenosti do cilja tj. rešenja) uz pomoć A* algortima pretrage stabla mogućih poteza. Neuronska mreža će biti trenirana pomoću reinforcement learning algoritma, pri čemu će biti korišćen approximate value iteration metod.

# Evaluacija

- Kao mera performanse za detektovanje strana kocke biće korišćena preciznost, odnosno procenat tačno određenih boja svakog od kvadrata kocke.
- Kao mera performanse za rešavanje kocke biće korišćen procenat rešenih stanja kocke (pri čemu se smatra da kocka nije rešena ukoliko broj poteza prelazi 150).

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by darkotica** [comment]
Link ka repozitorijumu: https://github.com/Dado555/rubex-cubex
